In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Đọc dữ liệu từ file CSV
df = pd.read_csv("coffee_shop_revenue.csv")

print(f"Kích thước tập dữ liệu ban đầu: {df.shape}")
df.head()

Kích thước tập dữ liệu ban đầu: (2000, 7)


   Number_of_Customers_Per_Day  Average_Order_Value  Operating_Hours_Per_Day  \
0                          152                 6.74                       14   
1                          485                 4.50                       12   
2                          398                 9.09                        6   
3                          320                 8.48                       17   
4                          156                 7.44                       17   

   Number_of_Employees  Marketing_Spend_Per_Day  Location_Foot_Traffic  \
0                    4                   106.62                     97   
1                    8                    57.83                    744   
2                    6                    91.76                    636   
3                    4                   462.63                    770   
4                    2                   412.52                    232   

   Daily_Revenue  
0        1547.81  
1        2084.68  
2        3118.39 

In [5]:
# Kiểm tra thông tin cấu trúc và kiểu dữ liệu của các cột
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Number_of_Customers_Per_Day  2000 non-null   int64  
 1   Average_Order_Value          2000 non-null   float64
 2   Operating_Hours_Per_Day      2000 non-null   int64  
 3   Number_of_Employees          2000 non-null   int64  
 4   Marketing_Spend_Per_Day      2000 non-null   float64
 5   Location_Foot_Traffic        2000 non-null   int64  
 6   Daily_Revenue                2000 non-null   float64
dtypes: float64(3), int64(4)
memory usage: 109.5 KB


In [ ]:
# Đếm số lượng giá trị NaN trong từng cột
missing_values = df.isnull().sum()
print("Số lượng missing values trong mỗi cột:\n", missing_values)

Số lượng missing values trong mỗi cột:
 Number_of_Customers_Per_Day    0
Average_Order_Value            0
Operating_Hours_Per_Day        0
Number_of_Employees            0
Marketing_Spend_Per_Day        0
Location_Foot_Traffic          0
Daily_Revenue                  0
dtype: int64


In [7]:
# Kiểm tra số lượng dòng trùng lặp
duplicates_count = df.duplicated().sum()
print(f"Số dòng dữ liệu bị trùng lặp: {duplicates_count}")

# Xóa các dòng trùng lặp (nếu có) và cập nhật lại DataFrame
if duplicates_count > 0:
    df = df.drop_duplicates()
    print(f"Kích thước dữ liệu sau khi xóa trùng lặp: {df.shape}")

Số dòng dữ liệu bị trùng lặp: 0


In [8]:
# Chuyển tên cột thành chữ thường
df.columns = df.columns.str.lower()

print("Tên cột sau khi chuẩn hóa:")
print(df.columns)

Tên cột sau khi chuẩn hóa:
Index(['number_of_customers_per_day', 'average_order_value',
       'operating_hours_per_day', 'number_of_employees',
       'marketing_spend_per_day', 'location_foot_traffic', 'daily_revenue'],
      dtype='object')


In [12]:
#. Lưu toàn bộ tập dữ liệu ra file CSV mới
df.to_csv("coffee_shop_revenue_cleaned.csv", index=False)
print(f"Đã lưu toàn bộ dữ liệu vào file: coffee_shop_revenue_cleaned.csv")
print(f"Kích thước tập dữ liệu: {df.shape}")

Đã lưu toàn bộ dữ liệu vào file: coffee_shop_revenue_cleaned.csv
Kích thước tập dữ liệu: (2000, 7)


In [13]:
# Thiết lập chung cho đồ thị
plt.style.use('seaborn-v0_8-whitegrid')

# 1. Thống kê mô tả
print("--- THỐNG KÊ MÔ TẢ TẬP DỮ LIỆU ---")
display(df.describe().round(2))

--- THỐNG KÊ MÔ TẢ TẬP DỮ LIỆU ---


       number_of_customers_per_day  average_order_value  \
count                      2000.00              2000.00   
mean                        274.30                 6.26   
std                         129.44                 2.18   
min                          50.00                 2.50   
25%                         164.00                 4.41   
50%                         275.00                 6.30   
75%                         386.00                 8.12   
max                         499.00                10.00   

       operating_hours_per_day  number_of_employees  marketing_spend_per_day  \
count                  2000.00              2000.00                  2000.00   
mean                     11.67                 7.95                   252.61   
std                       3.44                 3.74                   141.14   
min                       6.00                 2.00                    10.12   
25%                       9.00                 5.00                 

In [14]:
# 2. Histogram (Phân phối của doanh thu hàng ngày)
plt.figure(figsize=(8,5))
plt.hist(df['daily_revenue'], bins=20, edgecolor='black')
plt.title('Distribution of Daily Revenue')
plt.xlabel('Daily Revenue')
plt.ylabel('Frequency')
plt.show()

<Figure size 800x500 with 1 Axes>

Từ Hình 1 có thể thấy:
- Phân bố của biến doanh thu không tuân theo dạng chuẩn mà có xu hướng lệch phải rõ rệt (right-skewed).
- Tần suất doanh thu cao nhất tập trung trong khoảng từ 1.000 đến 2.000, cho thấy đây là mức vận hành phổ biến và ổn định của quán.
- Tuy nhiên, sự xuất hiện của các dải dữ liệu kéo dài về phía giá trị lớn (tiệm cận 5.000) và các điểm giá trị thấp (gần 0) cho thấy mô hình kinh doanh tồn tại những biến động nhất định, có thể xuất phát từ các ngày có sự kiện đặc biệt hoặc các yếu tố ngoại cảnh ngoài mong đợi.
- Từ góc độ kỹ thuật, phân bố lệch này là một chỉ dấu quan trọng: nó gợi ý rằng việc thực hiện các bước tiền xử lý như biến đổi Log (Log Transformation) hoặc chuẩn hóa dữ liệu chuyên sâu hơn sẽ là cần thiết trong các nghiên cứu tương lai, nhằm giảm thiểu ảnh hưởng của các giá trị ngoại lai và giúp mô hình hồi quy đạt được hiệu suất tối ưu hơn